import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        
        <div className="header">
          <div>Coolplanner</div>
          <div className="navigation">
            <Link href="/timetable">timetable</Link>
            <Link href="/activities">Activities</Link>
            <Link href="/timetable_elements">timetable_elements</Link>
          </div>
        </div>

        <main>{children}</main>
      </body>
    </html>
  );
}
